CREATE TABLE FRANQUICIA (
    ID_Franquicia SERIAL PRIMARY KEY,
    Nombre_Franquicia VARCHAR(150) NOT NULL,
    Desarrollador VARCHAR(150) NOT NULL
);

CREATE TABLE CATEGORIA (
    ID_Categoria SERIAL PRIMARY KEY,
    Nombre_Categoria VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PROVEEDOR (
    ID_Proveedor SERIAL PRIMARY KEY,
    Nombre_Proveedor VARCHAR(150) NOT NULL
);

CREATE TABLE CLIENTE (
    ID_Cliente SERIAL PRIMARY KEY,
    Nombre_Cliente VARCHAR(150) NOT NULL
);

CREATE TABLE EMPLEADO (
    ID_Empleado SERIAL PRIMARY KEY,
    Nombre_Empleado VARCHAR(150) NOT NULL
);

CREATE TABLE METODO_PAGO (
    ID_Metodo SERIAL PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE LOCAL (
    ID_Local SERIAL PRIMARY KEY,
    Nombre VARCHAR(150) NOT NULL,
    Zona VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCTO (
    ID_Producto SERIAL PRIMARY KEY,
    Nombre VARCHAR(150) NOT NULL,
    Descripcion TEXT NOT NULL,
    URL_Imagen TEXT,
    ID_Franquicia INT NOT NULL,
    Precio_Actual NUMERIC(10, 2) NOT NULL CHECK (Precio_Actual >= 0),
    CONSTRAINT fk_franquicia FOREIGN KEY (ID_Franquicia) 
        REFERENCES FRANQUICIA(ID_Franquicia) ON DELETE RESTRICT
);

CREATE TABLE COMPRA (
    ID_Compra SERIAL PRIMARY KEY,
    ID_Cliente INT NOT NULL,
    ID_Empleado INT NOT NULL,
    ID_Metodo INT NOT NULL,
    ID_Local INT NOT NULL,
    Fecha_Compra TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_cliente FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente) ON DELETE RESTRICT,
    CONSTRAINT fk_empleado FOREIGN KEY (ID_Empleado) REFERENCES EMPLEADO(ID_Empleado) ON DELETE RESTRICT,
    CONSTRAINT fk_metodo FOREIGN KEY (ID_Metodo) REFERENCES METODO_PAGO(ID_Metodo) ON DELETE RESTRICT,
    CONSTRAINT fk_local FOREIGN KEY (ID_Local) REFERENCES LOCAL(ID_Local) ON DELETE RESTRICT
);

CREATE TABLE PRODUCTO_CATEGORIA (
    ID_Producto INT NOT NULL,
    ID_Categoria INT NOT NULL,
    PRIMARY KEY (ID_Producto, ID_Categoria),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(ID_Producto) ON DELETE CASCADE,
    FOREIGN KEY (ID_Categoria) REFERENCES CATEGORIA(ID_Categoria) ON DELETE CASCADE
);

CREATE TABLE PRODUCTO_PROVEEDOR (
    ID_Producto INT NOT NULL,
    ID_Proveedor INT NOT NULL,
    PRIMARY KEY (ID_Producto, ID_Proveedor),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(ID_Producto) ON DELETE CASCADE,
    FOREIGN KEY (ID_Proveedor) REFERENCES PROVEEDOR(ID_Proveedor) ON DELETE CASCADE
);

CREATE TABLE INVENTARIO (
    ID_Producto INT NOT NULL,
    ID_Local INT NOT NULL,
    Cantidad_Actual INT NOT NULL DEFAULT 0 CHECK (Cantidad_Actual >= 0),
    PRIMARY KEY (ID_Producto, ID_Local),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(ID_Producto) ON DELETE CASCADE,
    FOREIGN KEY (ID_Local) REFERENCES LOCAL(ID_Local) ON DELETE CASCADE
);

CREATE TABLE COMPRA_PRODUCTOS (
    ID_Compra INT NOT NULL,
    ID_Producto INT NOT NULL,
    Cantidad INT NOT NULL CHECK (Cantidad > 0),
    Precio_Venta NUMERIC(10, 2) NOT NULL CHECK (Precio_Venta >= 0),
    PRIMARY KEY (ID_Compra, ID_Producto),
    FOREIGN KEY (ID_Compra) REFERENCES COMPRA(ID_Compra) ON DELETE RESTRICT,
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(ID_Producto) ON DELETE RESTRICT
);

